[package]
name = "bazaar"
version = "0.1.0"
authors = ["Naaman <naaman.the.dev@gmail.com>"]
edition = "2018"
default-run = "app"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "app"

[[bin]]
path = "src/generate_schema.rs"
name = "schema"

[dependencies]
actix-web = "3.3.0"
actix-rt = "1.1.1"
async-graphql = "2.1.5"
async-graphql-actix-web = "2.1.5"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"

sqlx = { version = "0.4.1", default-features = false, features = ["runtime-tokio-native-tls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"] }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
chrono = { version = "0.4.19", features = ["serde"] }
tokio = { version = "0.2.6", features = ["full"] }

dotenv = "0.15.0"
anyhow = "1.0.34"

tracing = "0.1.22"
tracing-subscriber = { version = "0.2.15", features = ["registry", "env-filter"] }
tracing-futures = "0.2.4"
tracing-log = "0.1.1"
tracing-bunyan-formatter = "0.1.7"
config = { version = "0.10.1", default-features = false, features = ["yaml"] }
graphql_client = "0.9.0"
tracing-actix-web = "0.2.1"
serde-aux = "1.1.0"
strum = { version = "0.20.0", features = ["derive"] } 

[dev-dependencies]
reqwest = { version = "0.10.9", features = ["json", "trust-dns"] } 
lazy_static = "1.4.0"
